package com.cris.training.paths;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: cris-training, path: /WEB-INF/ebx/cris-training.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface coachPaths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		41 path constants.
	//		19 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Coach
	{
		private static final Path _Root_Coach = _Root.add("Coach");
		public static Path getPathInSchema()
		{
			return _Root_Coach;
		}
		public static final Path _Root_Coach_Coach_id = Path.parse("./coach_id");
		public static final Path _Root_Coach_Coach_no = Path.parse("./coach_no");
		public static final Path _Root_Coach_Coach_type = Path.parse("./coach_type");
		public static final Path _Root_Coach_Coach_gauge = Path.parse("./coach_gauge");
		public static final Path _Root_Coach_Owning_railway = Path.parse("./owning_railway");
		public static final Path _Root_Coach_Owning_division = Path.parse("./owning_division");
		public static final Path _Root_Coach_Commissioning_date = Path.parse("./commissioning_date");
		public static final Path _Root_Coach_Built_date = Path.parse("./built_date");
		public static final Path _Root_Coach_Condemnation_date = Path.parse("./condemnation_date");
		public static final Path _Root_Coach_Coach_description = Path.parse("./coach_description");
		public static final Path _Root_Coach_Rfid_tag = Path.parse("./rfid_tag");
		public static final Path _Root_Coach_Coach_status = Path.parse("./coach_status");
		public static final Path _Root_Coach_Audit_info = Path.parse("./audit_info");
		public static final Path _Root_Coach_Audit_info_Source_record_id = Path.parse("./audit_info/source_record_id");
		public static final Path _Root_Coach_Audit_info_Source_event_type = Path.parse("./audit_info/source_event_type");
		public static final Path _Root_Coach_Audit_info_Source_system_name = Path.parse("./audit_info/source_system_name");
		public static final Path _Root_Coach_Coupling_type = Path.parse("./coupling_type");
	} 

	// Table type path
	public final class _Root_Coach_Type
	{
		private static final Path _Root_Coach_Type = _Root.add("Coach_Type");
		public static Path getPathInSchema()
		{
			return _Root_Coach_Type;
		}
		public static final Path _Root_Coach_Type_Coach_type = Path.parse("./coach_type");
		public static final Path _Root_Coach_Type_Coupling_type = Path.parse("./coupling_type");
		public static final Path _Root_Coach_Type_Power_generation_type = Path.parse("./power_generation_type");
	} 
	// ===============================================

}
