package com.bct.user.registration.paths;

import com.orchestranetworks.schema.*;

import com.orchestranetworks.schema.*;

/**
 * Generated by TIBCO EBX(R) 1214:0002, at 2023/03/22 23:14:01 [CET].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: user-registration, path: /WEB-INF/ebx/schemas/user_registration.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface UserRegistrationPaths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Statistics:
	//		106 path constants.
	//		45 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Root_Business_Users_Registration_Details
	{
		private static final Path _Root_Business_Users_Registration_Details = _Root.add("Business_Users_Registration_Details");
		public static Path getPathInSchema()
		{
			return _Root_Business_Users_Registration_Details;
		}
		public static final Path _Root_Business_Users_Registration_Details_Ipas_Id = Path.parse("./Ipas_Id");
		public static final Path _Root_Business_Users_Registration_Details_Name = Path.parse("./Name");
		public static final Path _Root_Business_Users_Registration_Details_Last_Name = Path.parse("./Last_Name");
		public static final Path _Root_Business_Users_Registration_Details_Designation = Path.parse("./Designation");
		public static final Path _Root_Business_Users_Registration_Details_Department = Path.parse("./Department");
		public static final Path _Root_Business_Users_Registration_Details_Entity = Path.parse("./Entity");
		public static final Path _Root_Business_Users_Registration_Details_User_Type = Path.parse("./User_Type");
		public static final Path _Root_Business_Users_Registration_Details_Zone = Path.parse("./Zone");
		public static final Path _Root_Business_Users_Registration_Details_Divison = Path.parse("./Divison");
		public static final Path _Root_Business_Users_Registration_Details_Shed = Path.parse("./Shed");
		public static final Path _Root_Business_Users_Registration_Details_Mdm_User_Id = Path.parse("./Mdm_User_Id");
		public static final Path _Root_Business_Users_Registration_Details_Mobile_Number = Path.parse("./Mobile_Number");
		public static final Path _Root_Business_Users_Registration_Details_Email = Path.parse("./Email");
		public static final Path _Root_Business_Users_Registration_Details_User_Register_Approval = Path.parse("./User_Register_Approval");
		public static final Path _Root_Business_Users_Registration_Details_Service_Status = Path.parse("./Service_Status");
		public static final Path _Root_Business_Users_Registration_Details_Asset_Designation_Code = Path.parse("./Asset_Designation_Code");
	} 

	// Table type path
	public final class _Root_User_Registration_Details
	{
		private static final Path _Root_User_Registration_Details = _Root.add("User_Registration_Details");
		public static Path getPathInSchema()
		{
			return _Root_User_Registration_Details;
		}
		public static final Path _Root_User_Registration_Details_Ipas_Id = Path.parse("./Ipas_Id");
		public static final Path _Root_User_Registration_Details_Name = Path.parse("./Name");
		public static final Path _Root_User_Registration_Details_Last_Name = Path.parse("./Last_Name");
		public static final Path _Root_User_Registration_Details_Designation = Path.parse("./Designation");
		public static final Path _Root_User_Registration_Details_Department = Path.parse("./Department");
		public static final Path _Root_User_Registration_Details_Service_Status = Path.parse("./Service_Status");
		public static final Path _Root_User_Registration_Details_Entity = Path.parse("./Entity");
		public static final Path _Root_User_Registration_Details_User_Type = Path.parse("./User_Type");
		public static final Path _Root_User_Registration_Details_Zone = Path.parse("./Zone");
		public static final Path _Root_User_Registration_Details_Divison = Path.parse("./Divison");
		public static final Path _Root_User_Registration_Details_Shed = Path.parse("./Shed");
		public static final Path _Root_User_Registration_Details_Mobile_Number = Path.parse("./Mobile_Number");
		public static final Path _Root_User_Registration_Details_Email = Path.parse("./Email");
		public static final Path _Root_User_Registration_Details_User_Register_Approval = Path.parse("./User_Register_Approval");
		public static final Path _Root_User_Registration_Details_Asset_Designation_Code = Path.parse("./Asset_Designation_Code");
		public static final Path _Root_User_Registration_Details_Allowed_Zones = Path.parse("./Allowed_Zones");
		public static final Path _Root_User_Registration_Details_Allowed_Divisions = Path.parse("./Allowed_Divisions");
		public static final Path _Root_User_Registration_Details_Allowed_Sheds = Path.parse("./Allowed_Sheds");
	} 

	// Table type path
	public final class _Root_User_Permissions_Zone
	{
		private static final Path _Root_User_Permissions_Zone = _Root.add("User_Permissions_Zone");
		public static Path getPathInSchema()
		{
			return _Root_User_Permissions_Zone;
		}
		public static final Path _Root_User_Permissions_Zone_Ipas_Id = Path.parse("./Ipas_Id");
		public static final Path _Root_User_Permissions_Zone_Zone_Code = Path.parse("./Zone_Code");
	} 

	// Table type path
	public final class _Root_User_Permissions_Division
	{
		private static final Path _Root_User_Permissions_Division = _Root.add("User_Permissions_Division");
		public static Path getPathInSchema()
		{
			return _Root_User_Permissions_Division;
		}
		public static final Path _Root_User_Permissions_Division_Ipas_Id = Path.parse("./Ipas_Id");
		public static final Path _Root_User_Permissions_Division_Division_Code = Path.parse("./Division_Code");
	} 

	// Table type path
	public final class _Root_User_Permissions_Shed
	{
		private static final Path _Root_User_Permissions_Shed = _Root.add("User_Permissions_Shed");
		public static Path getPathInSchema()
		{
			return _Root_User_Permissions_Shed;
		}
		public static final Path _Root_User_Permissions_Shed_Ipas_Id = Path.parse("./Ipas_Id");
		public static final Path _Root_User_Permissions_Shed_Shed_Code = Path.parse("./Shed_Code");
	} 

	// Table type path
	public final class _Root_Designation_Master
	{
		private static final Path _Root_Designation_Master = _Root.add("Designation_Master");
		public static Path getPathInSchema()
		{
			return _Root_Designation_Master;
		}
		public static final Path _Root_Designation_Master_Hrms_Designation = Path.parse("./Hrms_Designation");
		public static final Path _Root_Designation_Master_Entity = Path.parse("./Entity");
		public static final Path _Root_Designation_Master_Short_Designation = Path.parse("./Short_Designation");
		public static final Path _Root_Designation_Master_Ds_Role = Path.parse("./Ds_Role");
		public static final Path _Root_Designation_Master_Daa_Role = Path.parse("./Daa_Role");
	} 
	// ===============================================

}